In [2]:
import numpy as np
arr=np.array(np.arange(2,50,3))
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [14]:
import numpy as np
lst1=[]
lst2=[]
print("For lst1:")
for _ in range(5):
    lst1.append(eval(input()))
print("For lst2:")
for _ in range(5):
    lst2.append(eval(input()))
num_arr1=np.array(lst1)
num_arr2=np.array(lst2)
print(num_arr1+num_arr2) #concatination
print(np.sort(num_arr1))  #num_arr1 sorted
print(np.sort(num_arr2))  #num_arr2 sorted
print(np.sort(num_arr1+num_arr2))  #num_arr1 and num_arr2 concatenated & sorted

For lst1:
5
3
2
1
2
For lst2:
6
5
3
4
2
[11  8  5  5  4]
[1 2 2 3 5]
[2 3 4 5 6]
[ 4  5  5  8 11]


In [19]:
import numpy as np
arr1=np.array([input() for _ in range(int(input()))])
print(arr1)  #prints the numpy array
print(type(arr1)) #returns the type
print(arr1.shape)  #provides the dimensions
print(arr1.size*arr1.itemsize)  #size

5
Ananya
20
9.5
8/9/2000
done
['Ananya' '20' '9.5' '8/9/2000' 'done']
<class 'numpy.ndarray'>
(5,)
160


In [ ]:
Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [10]:
import numpy as np
arr=np.array([input() for _ in range(10)])
print(arr)
print(arr.reshape(5,2))

1
2
3
4
5
6
7
8
9
10
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']
[['1' '2']
 ['3' '4']
 ['5' '6']
 ['7' '8']
 ['9' '10']]


In [27]:
import numpy as np
print("arr1:")
arr1=np.array([input() for _ in range(4)])
print("arr2:")
arr2=np.array([input() for _ in range(4)])
print()
print(np.vstack((arr1,arr2)))  #vertical stack
print()
print(np.hstack((arr1,arr2)))  #horizontal stack

arr1:
1
2
3
4
arr2:
11
22
33
44

[['1' '2' '3' '4']
 ['11' '22' '33' '44']]

['1' '2' '3' '4' '11' '22' '33' '44']


In [9]:
import numpy as np
arr=np.array([input() for _ in range(int(input("Size of the array")))])
print(np.unique(arr)) #to get unique items
print(len(np.unique(arr))) #to get the counts of unique items


Size of the array6
1
2
1
2
3
4
['1' '2' '3' '4']
4
